### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by WaterBoyBia** [QikaiXu/Spam-Message-Recognition#1]
您好，请问一下数据集的下载地址怎么打不开呢？

**Comment by QikaiXu** [comment]
已经更新了数据集地址。 蓝奏云分享地址一直会变= =

**Comment by WaterBoyBia** [comment]
谢谢，已经下载到了数据集：）-------- 原始邮件 --------发件人： QikaiXu ***@***.***>日期： 2023年11月30日周四 15:19收件人： QikaiXu/Spam-Message-Recognition ***@***.***>抄送： WaterBoyBia ***@***.***>, Author ***@***.***>主    题： Re: [QikaiXu/Spam-Message-Recognition] 关于数据集的问题 (Issue #1)
已经更新了数据集地址。 蓝奏云分享地址一直会变= =
